# playbook.yml
- name: Configure Pacemaker cluster with master/slave resources
  hosts: localhost
  connection: local

  tasks:
    - name: Delete ipaddr
      resource_manager:
        name: ipaddr
        op_type: delete
      register: result

    - name: show result
      debug:
        var: result.msg

    - name: Delete bundle
      resource_manager:
        name: bundle1
        op_type: delete
      register: result

    - name: show result
      debug:
        var: result.msg

    - name: Delete res1
      resource_manager:
        name: res1
        op_type: delete
      register: result

    - name: show result
      debug:
        var: result.msg

    - name: Delete res2
      resource_manager:
        name: res2
        op_type: delete
      register: result

    - name: show result
      debug:
        var: result.msg


    