# playbook.yml
- name: Configure Pacemaker cluster with master/slave resources
  hosts: localhost
  connection: local

  tasks:
    - name: Ensure cluster is running
      command: pcs status
      register: cluster_status
      changed_when: false

    - name: Create promotable resource res1
      resource_manager:
        name: res1
        op_type: create
        agent: "ocf:pacemaker:Stateful"
      register: result

    - name: show result
      debug:
        var: result.msg

    - name: Create resource res2
      resource_manager:
        name: res2
        op_type: create
        agent: ocf:pacemaker:Dummy
      register: result

    - name: show result
      debug:
        var: result.msg

    - name: Add constraint on start
      constraint_manager:
        op_type: create
        constraint_type: order
        action_1: start
        action_1_resource: res1-clone
        action_2: start
        action_2_resource: res2
      register: result

    - name: show result
      debug:
        var: result.msg

    - name: Add constraint on promote
      constraint_manager:
        op_type: create
        constraint_type: order
        action_1: start
        action_1_resource: res2
        action_2: promote
        action_2_resource: res1-clone
      register: result

    - name: show result
      debug:
        var: result.msg

    - name: Add colocation constraint
      constraint_manager:
        op_type: create
        constraint_type: colocation
        action_1: promoted
        action_1_resource: res1-clone
        action_2_resource: res2
      register: result

    - name: show result
      debug:
        var: result.msg